const keywords_bank = [
  "Afghanistan",
  "Afrika Selatan",
  "Albania",
  "Aljazair",
  "Amerika Serikat",
  "Andorra",
  "Angola",
  "Antigua dan Barbuda",
  "Arab Saudi",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahama",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belanda",
  "Belarus",
  "Belgia",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia dan Herzegovina",
  "Botswana",
  "Brasil",
  "Britania Raya",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Ceko",
  "Chad",
  "Chili",
  "China",
  "Denmark",
  "Djibouti",
  "Dominika",
  "Ekuador",
  "El Salvador",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Etiopia",
  "Fiji",
  "Filipina",
  "Finlandia",
  "Gabon",
  "Gambia",
  "Georgia",
  "Ghana",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guinea Khatulistiwa",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hongaria",
  "India",
  "Indonesia",
  "Irak",
  "Iran",
  "Irlandia",
  "Islandia",
  "Israel",
  "Italia",
  "Jamaika",
  "Jepang",
  "Jerman",
  "Kamboja",
  "Kamerun",
  "Kanada",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kolombia",
  "Komoro",
  "Kongo",
  "Korea Selatan",
  "Korea Utara",
  "Kosta Rika",
  "Kroasia",
  "Kuba",
  "Kuwait",
  "Kirgizstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lituania",
  "Luksemburg",
  "Madagaskar",
  "Makedonia Utara",
  "Maladewa",
  "Malawi",
  "Malaysia",
  "Mali",
  "Malta",
  "Maroko",
  "Mauritania",
  "Mauritius",
  "Meksiko",
  "Mesir",
  "Mikronesia",
  "Moldova",
  "Monako",
  "Mongolia",
  "Montenegro",
  "Mozambik",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Niger",
  "Nigeria",
  "Nikaragua",
  "Norwegia",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Pantai Gading",
  "Papua Nugini",
  "Paraguay",
  "Peru",
  "Polandia",
  "Portugal",
  "Prancis",
  "Qatar",
  "Republik Dominika",
  "Republik Afrika Tengah",
  "Rumania",
  "Rusia",
  "Rwanda",
  "Saint Kitts dan Nevis",
  "Saint Lucia",
  "Saint Vincent dan Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome dan Principe",
  "Selandia Baru",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapura",
  "Siprus",
  "Slovenia",
  "Slowakia",
  "Solomon",
  "Somalia",
  "Sri Lanka",
  "Sudan",
  "Sudan Selatan",
  "Suriah",
  "Suriname",
  "Swedia",
  "Swiss",
  "Taiwan",
  "Tajikistan",
  "Tanjung Verde",
  "Tanzania",
  "Thailand",
  "Timor Leste",
  "Togo",
  "Tonga",
  "Trinidad dan Tobago",
  "Tunisia",
  "Turki",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraina",
  "Uni Emirat Arab",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yaman",
  "Yordania",
  "Yunani",
  "Zambia",
  "Zimbabwe",
  "Real Madrid",
  "Barcelona",
  "Manchester United",
  "Liverpool",
  "Bayern Munich",
  "Paris Saint-Germain",
  "Juventus",
  "AC Milan",
  "Inter Milan",
  "Boca Juniors",
  "River Plate",
  "Ajax Amsterdam",
  "Benfica",
  "Porto",
  "Celtic",
  "Rangers",
  "Borussia Dortmund",
  "Chelsea",
  "Arsenal",
  "Manchester City",
  "Atletico Madrid",
  "AS Roma",
  "Lazio",
  "Napoli",
  "Galatasaray",
  "Fenerbahce",
  "Besiktas",
  "Al-Hilal",
  "Al-Nassr",
  "Flamengo",
  "Corinthians",
  "Sao Paulo",
  "Palmeiras",
  "Pumas UNAM",
  "Club America",
  "Chivas Guadalajara",
  "Cruz Azul",
  "Sydney FC",
  "Melbourne Victory",
  "Kawasaki Frontale",
  "Urawa Red Diamonds",
  "Jeonbuk Hyundai Motors",
  "FC Seoul",
  "Zamalek",
  "Al-Ahly",
  "Mamelodi Sundowns",
  "Kaizer Chiefs",
  "Club Brugge",
  "Anderlecht",
  "Zenit Saint Petersburg",
  "Spartak Moscow",
  "Shakhtar Donetsk",
  "Dynamo Kyiv",
  "Everest",
  "K2",
  "Kangchenjunga",
  "Lhotse",
  "Makalu",
  "Cho Oyu",
  "Dhaulagiri",
  "Manaslu",
  "Nanga Parbat",
  "Annapurna",
  "Gasherbrum I",
  "Broad Peak",
  "Shishapangma",
  "Aconcagua",
  "Denali",
  "Elbrus",
  "Vinson",
  "Puncak Jaya",
  "Mont Blanc",
  "Kilimanjaro",
  "Fuji",
  "Matterhorn",
  "Vesuvius",
  "Mauna Kea",
  "Mauna Loa",
  "Cotopaxi",
  "Chimborazo",
  "Merapi",
  "Krakatau",
  "Tambora",
  "Semeru",
  "Rinjani",
  "Bromo",
  "Agung",
  "Lawu",
  "Ijen",
  "Merbabu",
  "Sinabung",
  "Kelimutu",
  "Kerinci",
  "Kinabalu",
  "Apo",
  "Popocatepetl",
  "Orizaba",
  "St. Helens",
  "Rainier",
  "Etna",
  "Ararat",
  "Klyuchevskaya Sopka",
  "Yellowstone",
  "Eyjafjallajokull",
  "Hekla",
  "Cook",
  "Ruapehu",
  "Osorno",
  "Misti",
  "Sangay",
  "Toliman",
  "Meru",
  "Kenya",
  "Ras Dashen",
  "Kibo",
  "Maromokotro",
  "Olympus",
  "Kosciusko",
  "Mont Blanc",
  "Pico Bolívar",
  "Pico da Neblina",
  "Gora Elbrus",
  "Puncak Trikora",
  "Puncak Mandala",
  "Jaya Wijaya",
  "Cartensz",
  "Soekarno",
  "Mohammad Hatta",
  "Jenderal Soedirman",
  "Pangeran Diponegoro",
  "Cut Nyak Dien",
  "R.A. Kartini",
  "Tuanku Imam Bonjol",
  "Pattimura",
  "Sultan Hasanuddin",
  "Ki Hajar Dewantara",
  "Mohammad Hoesni Thamrin",
  "H.O.S. Cokroaminoto",
  "Agus Salim",
  "Sutan Sjahrir",
  "Ir. Djuanda Kartawidjaja",
  "Fatmawati",
  "Cut Nyak Meutia",
  "Martha Christina Tiahahu",
  "I Gusti Ngurah Rai",
  "Frans Kaisiepo",
  "Sri Sultan Hamengkubuwono IX",
  "Wage Rudolf Soepratman",
  "Kapitan Pattimura",
  "Otto Iskandardinata",
  "Teuku Umar",
  "Tjokroaminoto",
  "Mohammad Yamin",
  "Ahmad Yani",
  "Supriyadi",
  "Adnan Kapau Gani",
  "Abdul Muis",
  "Sultan Agung Hanyokrokusumo",
  "Pangeran Antasari",
  "Dewi Sartika",
  "Jenderal Gatot Subroto",
  "Pangeran Sambernyawa",
  "Sultan Mahmud Badaruddin II",
  "Muhammad Husni Thamrin",
  "Abdul Haris Nasution",
  "Yos Sudarso",
  "Piere Tendean",
  "Ki Bagus Hadikusumo",
  "Sultan Syarif Kasim II",
  "R. E. Martadinata",
  "Adam Malik",
  "Mohammad Natsir",
  "Umar Wirahadikusumah",
  "Bung Tomo",
  "Soepomo",
  "Achmad Soebardjo",
  "Tan Malaka",
  "Abdul Halim",
  "Abdul Wahab Hasbullah",
  "KH. Hasyim Asy'ari",
  "KH. Ahmad Dahlan",
  "Abdul Rachman Saleh",
  "Raden Patah",
  "Dipati Ukur",
  "Sisingamangaraja XII",
  "Aceh",
  "Banda Aceh",
  "Sumatera Utara",
  "Medan",
  "Sumatera Barat",
  "Padang",
  "Riau",
  "Pekanbaru",
  "Jambi",
  "Jambi",
  "Sumatera Selatan",
  "Palembang",
  "Bengkulu",
  "Bengkulu",
  "Lampung",
  "Bandar Lampung",
  "Kepulauan Bangka Belitung",
  "Pangkalpinang",
  "Kepulauan Riau",
  "Tanjung Pinang",
  "DKI Jakarta",
  "Jakarta",
  "Jawa Barat",
  "Bandung",
  "Jawa Tengah",
  "Semarang",
  "Daerah Istimewa Yogyakarta",
  "Yogyakarta",
  "Jawa Timur",
  "Surabaya",
  "Banten",
  "Serang",
  "Bali",
  "Denpasar",
  "Nusa Tenggara Barat",
  "Mataram",
  "Nusa Tenggara Timur",
  "Kupang",
  "Kalimantan Barat",
  "Pontianak",
  "Kalimantan Tengah",
  "Palangka Raya",
  "Kalimantan Selatan",
  "Banjarmasin",
  "Kalimantan Timur",
  "Samarinda",
  "Kalimantan Utara",
  "Tanjung Selor",
  "Sulawesi Utara",
  "Manado",
  "Sulawesi Tengah",
  "Palu",
  "Sulawesi Selatan",
  "Makassar",
  "Sulawesi Tenggara",
  "Kendari",
  "Gorontalo",
  "Gorontalo",
  "Sulawesi Barat",
  "Mamuju",
  "Maluku",
  "Ambon",
  "Maluku Utara",
  "Sofifi",
  "Papua",
  "Jayapura",
  "Papua Barat",
  "Manokwari",
  "Papua Selatan",
  "Merauke",
  "Papua Tengah",
  "Nabire",
  "Papua Pegunungan",
  "Jayawijaya",
  "Apel",
  "Mangga",
  "Pisang",
  "Anggur",
  "Jeruk",
  "Stroberi",
  "Semangka",
  "Nanas",
  "Alpukat",
  "Lemon",
  "Kiwi",
  "Pepaya",
  "Jambu",
  "Delima",
  "Pir",
  "Ceri",
  "Bluberi",
  "Raspberi",
  "Kurma",
  "Leci",
  "Naga",
  "Mangga",
  "Nangka",
  "Rambutan",
  "Durian",
  "Manggis",
  "Salak",
  "Kelengkeng",
  "Markisa",
  "Sirsak",
  "Srikaya",
  "Melon",
  "Blewah",
  "Jeruk bali",
  "Jeruk nipis",
  "Jeruk purut",
  "Sawo",
  "Duku",
  "Jamblang",
  "Kedondong",
  "Belimbing",
  "Cempedak",
  "Gandaria",
  "Buni",
  "Kersen",
  "Kesemek",
  "Kemang",
  "Matoa",
  "Mirabelle",
  "Persik",
  "Aprikot",
  "Plum",
  "Zaitun",
  "Cranberry",
  "Blackcurrant",
  "Redcurrant",
  "Gooseberry",
  "Fig",
  "Kurma",
  "Ara",
  "Kelapa",
  "Buah tin",
  "Açaí",
  "Acerola",
  "Bael",
  "Caimito",
  "Carambola",
  "Cranberry",
  "Cupuaçu",
  "Feijoa",
  "Jabuticaba",
  "Jackfruit",
  "Longan",
  "Lucuma",
  "Lychee",
  "Miracle fruit",
  "Monstera",
  "Naranjilla",
  "Pawpaw",
  "Persimmon",
  "Pomegranate",
  "Quince",
  "Rambutan",
  "Salak",
  "Sapote",
  "Sapodilla",
  "Soursop",
  "Star apple",
  "Star fruit",
  "Tamarind",
  "Yangmei",
  "Yuzu",
  "Nasi goreng",
  "Sate",
  "Rendang",
  "Gudeg",
  "Pempek",
  "Soto",
  "Bakso",
  "Mie ayam",
  "Gado-gado",
  "Rawon",
  "Ketoprak",
  "Lontong sayur",
  "Tahu campur",
  "Coto Makassar",
  "Bika Ambon",
  "Klepon",
  "Cenil",
  "Lumpia",
  "Martabak",
  "Kerak telor",
  "Batagor",
  "Cireng",
  "Tahu gejrot",
  "Sate padang",
  "Nasi uduk",
  "Nasi kuning",
  "Serabi",
  "Otak-otak",
  "Asinan Betawi",
  "Gulai",
  "Opor ayam",
  "Semur jengkol",
  "Sayur asem",
  "Pecel lele",
  "Pecel",
  "Rujak",
  "Empek-empek",
  "Kue putu",
  "Kue cubit",
  "Cilok",
  "Seblak",
  "Siomay",
  "Lemper",
  "Risoles",
  "Pastel",
  "Nagaso",
  "Dadar gulung",
  "Kue lapis",
  "Onde-onde",
  "Kerupuk",
  "Es teler",
  "Es dawet",
  "Es cendol",
  "Wedang ronde",
  "Sekoteng",
  "Bandrek",
  "Bajigur",
  "Bir pletok",
  "Papeda",
  "Ayam betutu",
  "Bebek goreng",
  "Sambal",
  "Tempe mendoan",
  "Tahu bulat",
  "Telur gulung",
  "Lapis legit",
  "Kue pukis",
  "Ongol-ongol",
  "Getuk",
  "Gethuk",
  "Payung Teduh",
  "Efek Rumah Kaca",
  "Fourtwnty",
  "Barasuara",
  "Danilla",
  "Maliq & D'Essentials",
  "The S.I.G.I.T",
  "Pure Saturday",
  "Naif",
  "Sore",
  "White Shoes & The Couples Company",
  "Endah N Rhesa",
  "Reality Club",
  "Ikkubaru",
  "Float",
  "Stars and Rabbit",
  "Tulus",
  "Isyana Sarasvati",
  "Raisa",
  "Jejak",
  "Dialog Dini Hari",
  "Folk",
  "Pandai Besi",
  "The Adams",
  "Feast",
  "Senar Senja",
  "Silampukau",
  "Polka Wars",
  "Rumahsakit",
  "Sheila On 7",
  "Kunto Aji",
  "Sore",
  "Lala Karmela",
  "Jason Ranti",
  "Amigdala",
  "Elephant Kind",
  "Goodnight Electric",
  "The Upstairs",
  "Adhitia Sofyan",
  "Mocca",
  "Gugun Blues Shelter",
  "The Panturas",
  "Sajama Cut",
  "Sir Lommar John",
  "Anjing",
  "Tigapagi",
  "The Jansen",
  "Dried Cassava",
  "The Changcuters",
  "The Sigit",
  "The Coconuttreez",
  "Diskopantera",
  "Padi Reborn",
  "Project Pop",
  "Kahitna",
  "D'Masiv",
];